### ISSUE TITLE
Seriespapaya source apparently not working

### ISSUE THREAD

**Issue by malversoft** [alfa-addon/alfa-repo-archive#13]
Series search works.
But any serie chapter produces empty list of sources.
Add to library also does not work.

Checked that the web seriespapaya.nu is up and working, and the chapters have their corresponding lists of sources there.

**Comment by shlibidon** [comment]
More info please, wich serie are you testing? wich category? device?
Cus it's working fine for me

https://alfa-addon.com/link-forums/pasos-para-un-correcto-reporte-de-error.24/

**Comment by malversoft** [comment]
Sorry, I think I was too fast. I crossposted in the wrong Github repository and with not enough detail. Now I have done more testing and I can report more accurately.

More info, details and debug log in the appropiate place:
https://github.com/alfa-addon/addon/issues/875

This issue can be closed, as it does not correspond to the alfa-repo, but to the alfa-addon.
