### ISSUE TITLE
seriesdanko mispelisyseries y newpct con algunos problemas

### ISSUE THREAD

**Issue by xiquillo** [alfa-addon/alfa-repo-archive#7]
Hola, seriesdanko mispelisyseries y newpct con algunos problemas, Seriesdanko cuando intentas ver algún enlace dice no hay nada que reproducir en todo ellos, mispelisyseries no se puede descargar el archivo torrent en la películas y en las series no hay elementos que mostrar cuando intentas ver los enlaces de las series y newpct no se puede descargar el archivo torrent , gracias por el addons y por la ayuda que dais.

**Comment by xiquillo** [comment]
Hola, seriesdanko mispelisyseries y newpct con algunos problemas, Seriesdanko cuando intentas ver algún enlace dice no hay nada que reproducir en todo ellos, mispelisyseries no se puede descargar el archivo torrent en la películas y en las series no hay elementos que mostrar cuando intentas ver los enlaces de las series y newpct no se puede descargar el archivo torrent , gracias por el addons y por la ayuda que dais.

**Comment by alfa-add-on** [comment]
corregido
